---
- name: Check if bbb_ssl_email is defined
  assert:
    that:
      - bbb_ssl_email != ""
  tags:
    - bbb-check_vars1

- name: Install LetsEncrypt enabled nginx config
  template:
    src: templates/bbb-ssl.conf.j2
    dest: /etc/nginx/sites-available/bigbluebutton
    backup: yes
  tags:
    - bbb_install_nginx_ssl_conf

- name: Update http for https on nginx
  replace:
    path: /opt/freeswitch/conf/sip_profiles/external.xml
    regexp: '<param name="ws-binding"  value=":5066"/>'
    replace: '<param name="wss-binding"  value="{{ server_ip }}:7443"/>'
    backup: yes
  tags:
    - bbb_enable_https

- name: Update http for https on nginx
  replace:
    path: /etc/bigbluebutton/nginx/sip.nginx
    regexp: 'http:'
    replace: 'https:'
    backup: yes
  tags:
    - bbb_enable_https

- name: Update SIP port on nginx
  replace:
    path: /etc/bigbluebutton/nginx/sip.nginx
    regexp: '5066'
    replace: '7443'
    backup: yes
  tags:
    - bbb_enable_https

- name: Update http for https on BigBlueButton webapp
  replace:
    path: "/usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties"
    regexp: 'bigbluebutton.web.serverURL=http:'
    replace: 'bigbluebutton.web.serverURL=https:'
    backup: yes
  tags:
    - bbb_enable_https

- name: Update http for https on red5
  replace:
    path: /usr/share/red5/webapps/screenshare/WEB-INF/screenshare.properties
    regexp: 'jnlpUrl=http:'
    replace: 'jnlpUrl=https:'
    backup: yes
  tags:
    - bbb_enable_https

- name: Update http for https on red5
  replace:
    path: /usr/share/red5/webapps/screenshare/WEB-INF/screenshare.properties
    regexp: 'jnlpFile=http:'
    replace: 'jnlpFile=https:'
    backup: yes
  tags:
    - bbb_enable_https

- name: Update http for https on BigBlueButton client config
  replace:
    path: /var/www/bigbluebutton/client/conf/config.xml
    regexp: 'http://'
    replace: 'https://'
    backup: yes
  tags:
    - bbb_enable_https

- name: Update http for https on BigBlueButton client config
  replace:
    path: /usr/local/bigbluebutton/core/scripts/bigbluebutton.yml
    regexp: 'playback_protocol: http$'
    replace: 'playback_protocol: https'
    backup: yes
  tags:
    - bbb_enable_https

- name: Ansible check if /var/lib/tomcat7/webapps/demo/bbb_api_conf.jsp exists
  stat:
    path: /var/lib/tomcat7/webapps/demo/bbb_api_conf.jsp
  register: demo
  tags:
    - bbb_enable_https

- name: Update http for https on demo
  replace:
    path: /var/lib/tomcat7/webapps/demo/bbb_api_conf.jsp
    regexp: 'String BigBlueButtonURL = "http:'
    replace: 'String BigBlueButtonURL = "https:'
    backup: yes
  when: demo.stat.exists == True
  tags:
    - bbb_enable_https
